### ISSUE TITLE
I cannot import java class LAPTrackerFactory in my jupyter notebook

### ISSUE THREAD

**Issue by FX28** [scijava/scyjava#58] opened 2023-03-31 18:29 UTC
![image](https://user-images.githubusercontent.com/63152804/229198482-1d0c37bf-20dd-4f19-bbec-e167b1b45b74.png)
![image](https://user-images.githubusercontent.com/63152804/229198577-84df5c0d-f46d-4914-9544-8cfd3d8f44a8.png)
As it is shown by the screenshots above, I cannot import LAPTrackerFactory. However, when I learn from other people's codes, I find that the class fiji.plugin.trackmate.tracking.oldlap.LAPTrackerFactory do exist. Evidence here: 
(https://python.hotexamples.com/examples/fiji.plugin.trackmate.tracking.oldlap/LAPTrackerFactory/-/python-laptrackerfactory-class-examples.html#0x6f556f79db45f56af5114b6f2b34d4142e65e9799ca0cfea5e87b52a9e9c812d-48,,78,
https://www.tabnine.com/code/java/classes/fiji.plugin.trackmate.tracking.oldlap.LAPTrackerFactory)
I am not familiar with the Java language. How can I deal with this? Please give some pieces of advice for me. Thanks!

**Comment by tinevez** [comment] 2023-03-31 21:12
Duplicate of this:
https://forum.image.sc/t/i-cannot-import-java-class-laptrackerfactory-in-my-jupyter-notebook/79353

**Closed by tinevez** 2023-03-31 21:12 UTC
