### ISSUE TITLE
Windows10 Warning in tests: "Windows fatal exception: access violation"

### ISSUE THREAD

**Issue by mpinkert** [scijava/scyjava#15] opened 2020-03-16 14:51 UTC
I am encountering an issue where running unit tests on any code that imports scyjava produces long warning outputs under the header of a "Windows fatal exception: access violation".  This error only occurs on Windows10; running the code with Ubuntu works fine.

The code still runs and completes successfully, but there is a lot of garbage output that clutters the console.  Do you all have any idea what might be causing it?

This is a minimum example of a Python 3.8.2 conda environment with just scyjava and pytest imported.  (Unittest also produces this output though).  
```python3
import scyjava

class TestImporting(object):
        def test_import(self):
                assert True
```
and yields this stack trace.

```
collecting ... Windows fatal exception: access violation

Current thread 0x00001474 (most recent call first):
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\six.py", line 856 in __new__
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\jnius\reflect.py", line 17 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 783 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\jnius\__init__.py", line 33 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 783 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\scyjava\__init__.py", line 131 in _init_jvm
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\scyjava\__init__.py", line 140 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 783 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "C:\Users\Michael\Documents\GitHub\access_violation_tester\test\test_access.py", line 1 in <module>
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\assertion\rewrite.py", line 152 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\py\_path\local.py", line 701 in pyimport
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\python.py", line 513 in _importtestmodule
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\python.py", line 445 in _getobj
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\python.py", line 263 in obj
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\python.py", line 461 in _inject_setup_module_fixture
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\python.py", line 448 in collect
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\runner.py", line 264 in <lambda>
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\runner.py", line 244 in from_call
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\runner.py", line 264 in pytest_make_collect_report
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\callers.py", line 187 in _multicall
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\manager.py", line 84 in <lambda>
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\manager.py", line 93 in _hookexec
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\hooks.py", line 286 in __call__
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\runner.py", line 382 in collect_one_node
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\main.py", line 654 in _matchnodes
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\main.py", line 629 in matchnodes
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\main.py", line 574 in _collect
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\main.py", line 498 in collect
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\runner.py", line 264 in <lambda>
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\runner.py", line 244 in from_call
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\runner.py", line 264 in pytest_make_collect_report
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\callers.py", line 187 in _multicall
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\manager.py", line 84 in <lambda>
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\manager.py", line 93 in _hookexec
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\hooks.py", line 286 in __call__
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\runner.py", line 382 in collect_one_node
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\main.py", line 476 in _perform_collect
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\main.py", line 452 in perform_collect
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\main.py", line 257 in pytest_collection
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\callers.py", line 187 in _multicall
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\manager.py", line 84 in <lambda>
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\manager.py", line 93 in _hookexec
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\hooks.py", line 286 in __call__
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\main.py", line 246 in _main
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\main.py", line 191 in wrap_session
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\main.py", line 240 in pytest_cmdline_main
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\callers.py", line 187 in _multicall
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\manager.py", line 84 in <lambda>
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\manager.py", line 93 in _hookexec
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\pluggy\hooks.py", line 286 in __call__
  File "C:\Users\Michael\Miniconda3\envs\access_violation\lib\site-packages\_pytest\config\__init__.py", line 124 in main
  File "C:\Users\Michael\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\193.5662.61\plugins\python\helpers\pycharm\_jb_pytest_runner.py", line 42 in <module>
```

**Comment by ctrueden** [comment] 2020-11-06 04:31
@hinerm Since you have the new JPype-based version of scyjava working on your Windows 10 box: could you please test whether this is still an issue?

**Comment by hinerm** [comment] 2020-11-17 19:14
I'm unable to reproduce this issue manually on Windows.

**Comment by ctrueden** [comment] 2020-11-17 20:01
Thanks for testing, @hinerm. Did you attempt to reproduce using the existing pyjnius release? Or only jpype?

If you _can_ reproduce with the pyjnius-based version, but _not_ with the new jpype-based one, we should certainly close this. Even if you can't reproduce with either... maybe we should still close it. Can always reopen if anyone else encounters the issue in future.

**Comment by hinerm** [comment] 2020-11-17 21:10
@ctrueden I can't reproduce the problem in the existing pyjnius release either. Maybe I'm testing it wrong? Here's what I'm doing:

1. Start an interactive shell
2. Execute the import and class definition
3. Instantiate the `TestImporting` class and call `test_import`

**Comment by imagejan** [comment] 2020-11-17 21:16
@hinerm what if you put that code in a `test_something.py` file and run `pytest` from that folder?

**Comment by hinerm** [comment] 2020-11-17 21:30
@imagejan the test passes but I have to run it from the `scyjava` folder. I assume there's a proper way for `pytest` to gain access to your conda environment, but it wasn't immediately obvious to me.

**Comment by hinerm** [comment] 2020-11-19 16:40
Closing for now and we can reopen if this becomes reproducible in the future

**Closed by hinerm** 2020-11-19 16:40 UTC
