### ISSUE TITLE
Discussion: level of extensibility in scyjava components

### ISSUE THREAD

**Issue by hinerm** [scijava/scyjava#23] opened 2020-12-09 20:38 UTC
Currently, the following is true about software built on `scyjava`:
1. At some point [start_jvm](https://github.com/scijava/scyjava/blob/89e1aa9142b71abe2a33aab170894555127ae1b7/scyjava/__init__.py#L18) needs to be called
1. Before doing so, [add_endpoint](https://github.com/scijava/scyjava/blob/89e1aa9142b71abe2a33aab170894555127ae1b7/scyjava/config/__init__.py#L23) needs to be called to cover each required java component
1. By the nature of [jgo](https://github.com/scijava/jgo), the most specific endpoint needs to be listed first to avoid unexpected dependency skew

Currently this is causing problems in `pyimagej` because:
* `imglyb` adds its endpoint in [__init__.py](https://github.com/imglib/imglyb/blob/3065bb4da74752a3066b6a082fb777a95b6683ff/imglyb/__init__.py#L19)
* `pyimagej` allows flexible specification of a target endpoint when it [spins up the scyjava jvm](https://github.com/imagej/pyimagej/blob/f6eca56ed2e288097ba45abef6046667c5d5ed20/imagej/__init__.py#L153), but at that point it has already [imported imglyb](https://github.com/imagej/pyimagej/blob/f6eca56ed2e288097ba45abef6046667c5d5ed20/imagej/__init__.py#L36) and thus `imglyb` is first on the `scyjava` endpoints list.

This can be fixed in `pyimagej` by moving the `imglyb` import after its own calls to `add_endpoint`, but this smells of future problems with extensibility.

For example, what if a downstream project wants to use `pyimagej` and also has their own java endpoint?  They can't use `pyimagej`'s `init` method - they'll have to write their own, adding their desired `imagej` endpoint after their own.

I believe our requirements are:
1. It should be possible to simply `import` any of the `scyjava` stack modules without to explicitly adding corresponding endpoints
1. It should be possible to call `scyjava.start_jvm` without explicitly adding any endpoints
1. It should be possible to override endpoints with desired versions

To satisfy these requirements I propose:
1. All `scyjava` stack modules should add their `RELEASE` endpoint in their `__init__.py`
1. This mechanism of adding endpoints should *prepend* to the list such that the last endpoint added comes first and "wins" in `jgo`
1. Subsequent calls to `add_endpoint` with a `groupId:artifactId` already in the list of endpoints should update the corresponding GAV in the endpoint list, without changing its position in the list.

**Comment by hinerm** [comment] 2020-12-09 20:41
@ctrueden I wanted to get your feedback on this before making a decision on implementation, because I don't know if I'm missing any requirements.

I also think my proposed solution isn't flexible enough to account for the potential differences in plain imagej vs imagej-legacy+fiji... or maybe it is and the `net:imagej:imagej` is what gets added in `__init__.py`, and leagcy+fiji are added if desired.

@elevans please take a look and let me know if anything doesn't make sense

**Comment by ctrueden** [comment] 2020-12-09 20:53
See also imagej/pyimagej#94.

@hinerm Thanks for the detailed analysis. I think in order to make a decision here, we need to be fully cognizant of what jgo is doing under the hood, and how it leans on Maven to do version management when there are multiple endpoints. Each endpoint is, by default, added not only as a dependency in the `dependencies` section of the synthesized POM, but also to the `dependencyManagement` section as well with import scope, such that its parent POM's dependency management will be imported. To understand why, see scijava/jgo#9 and related links there.

I agree with all three of the requirements on your list. I'm not 100% certain right now why, when `net.imglib2:imglib2-imglyb` is the first endpoint, its dependency management takes over _even if an explicit version is given for later endpoints_. This is a Maven question: if you give a hardcoded `<version>` in the `<dependency>`, I thought that still took precedence (though Eclipse warns about this) when Maven resolves the dependency versions. I think we'll need to dig a bit, to fully (re)comprehend how Maven works here, and then subsequently decide how we want jgo to work here.

I hope that helps. As always, let me know if you need help.

**Comment by hinerm** [comment] 2021-01-11 19:39
@elevans do you remember how to reproduce the error of not being able to load old versions of ImageJ?

```
import imagej
ij = imagej.init(['net.imagej:imagej:2.0.0-rc-71', 'net.imagej:imagej-legacy:0.37.4'])
ij.getVersion()
```

is producing `2.0.0-rc-71`... but I thought a few weeks ago it didn't?

**Comment by elevans** [comment] 2021-01-12 15:22
@hinerm Yeah! The problem stems from the some strange order preference with the endpoints. For example , if `net.imglib2:imglib2-imglyb:1.0.0` is the first endpoint then imagej version 2.1.0 is loaded regardless of what the user specified in the endpoint list. IIRC this is because `net.imglib2:imglib2-imglyb:1.0.0` depends on IJ and requests 2.1.0.

One hacky way this can be fixed is by moving the import of imglyb after setting the endpoints.

**Comment by hinerm** [comment] 2021-03-08 15:23
Note that although the ordering of endpoints change does allow endpoints to be specified, it does NOT fix the problem [reported here](https://github.com/imagej/pyimagej/issues/103) of version selection not working.

**Comment by hinerm** [comment] 2021-03-24 19:10
@ctrueden @elevans so I can not reproduce the issue that triggered this any more. I ran through all the [initialization methods](https://github.com/imagej/pyimagej/blob/master/doc/Initialization.md) and everything seemed to work fine - aside from a typo in one and a problem with the latest Fiji (due to filament detector).

I am wondering if we were mistaking failing `imagej.init` calls that only specified an imagej endpoint (e.g. `imagej.init(2.0.0-rc-72)`) which I fixed separately in https://github.com/imagej/pyimagej/commit/0fbf7155953d89515865343eeaeff37d3617c0c9 by removing the mandatory dependency on `imagej-legacy`. I'm inclined to leave everything else alone for now unless we can reproduce the version mismatches.

**Comment by elevans** [comment] 2021-03-29 16:30
@hinerm I just recently reinstalled my OS on my laptop so all my environments are fresh. I'll run through this again and see if I can reproduce the bug and confirm you experience.

**Comment by elevans** [comment] 2021-03-29 17:08
@hinerm Okay I ran through all the [initialization methods](https://github.com/imagej/pyimagej/blob/master/doc/Initialization.md) you did and here are my results. I'm using conda and installed the pyimagej env as instructed in our readme. System is Ubuntu 20.04 LTS

### `ij = imagej.init()`
```python
>>> ij = imagej.init()
>>> ij.getVersion()
'2.2.0/1.53c'
```

### ` ij = imagej.init('2.1.0')`
```python
>>> ij = imagej.init('2.1.0')
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Traceback (most recent call last):
  File "AbstractGateway.java", line 135, in org.scijava.AbstractGateway.get
  File "Context.java", line 324, in org.scijava.Context.service
  File "Types.java", line 155, in org.scijava.util.Types.load
  File "Types.java", line 226, in org.scijava.util.Types.load
  File "ClassLoader.java", line 522, in java.lang.ClassLoader.loadClass
  File "ClassLoaders.java", line 178, in jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass
  File "BuiltinClassLoader.java", line 581, in jdk.internal.loader.BuiltinClassLoader.loadClass
java.lang.ClassNotFoundException: java.lang.ClassNotFoundException: net.imagej.legacy.LegacyService

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "AbstractGateway.java", line 135, in org.scijava.AbstractGateway.get
  File "Context.java", line 324, in org.scijava.Context.service
  File "Types.java", line 155, in org.scijava.util.Types.load
  File "Types.java", line 234, in org.scijava.util.Types.load
  File "Types.java", line 975, in org.scijava.util.Types.iae
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/edward/Documents/software/anaconda/envs/pyimagej/lib/python3.8/site-packages/imagej/__init__.py", line 194, in init
    legacyServiceObj = ij.get('net.imagej.legacy.LegacyService')
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot load class: net.imagej.legacy.LegacyService

```
### `ij = imagej.init('net.imagej:imageJ:2.1.0', headless=False)`
```python
>>> ij = imagej.init('net.imagej:imageJ:2.1.0', headless=False)
Error in `/home/edward/Documents/software/anaconda/envs/pyimagej/bin/mvn -B -f /home/edward/.jgo/net.imglib2/imglib2-imglyb/1.0.0+net.imagej-imageJ-2.1.0+net.imagej-imagej-legacy-RELEASE/pom.xml dependency:resolve': 1
```

### `ij = imagej.init(['net.imagej:imagej', 'net.imagej:imagej-legacy'])`
```python
>>> ij = imagej.init(['net.imagej:imagej', 'net.imagej:imagej-legacy'])
>>> ij.getVersion()
'2.2.0/1.53c'
```

### `ij = imagej.init('sc.fiji:fiji')`
**Note: I know this one doesn't work due to an unrelated issue -- but normally does on my system.**
```python
>>> ij = imagej.init('sc.fiji:fiji')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/edward/Documents/software/anaconda/envs/pyimagej/lib/python3.8/site-packages/imagej/__init__.py", line 168, in init
    ij = ImageJ()
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Invalid service: sc.fiji.filamentdetector.gui.GUIStatusService
```

### `ij = imagej.init('sc.fiji:fiji:2.1.1')`
```python
>>> ij = imagej.init('sc.fiji:fiji:2.1.1')
>>> ij.getVersion()
'2.1.0/1.53c'
```

### `ij = imagej.init('path')`
```python
>>> ij = imagej.init('eds/fiji/path')
>>> ij.getVersion()
'2.1.0/1.53c
```

### `ij = imagej.init(['net.imagej:imagej', 'net.preibisch:BigStitcher'])`
```python
>>> ij = imagej.init(['net.imagej:imagej', 'net.preibisch:BigStitcher'])
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Traceback (most recent call last):
  File "AbstractGateway.java", line 135, in org.scijava.AbstractGateway.get
  File "Context.java", line 324, in org.scijava.Context.service
  File "Types.java", line 155, in org.scijava.util.Types.load
  File "Types.java", line 226, in org.scijava.util.Types.load
  File "ClassLoader.java", line 522, in java.lang.ClassLoader.loadClass
  File "ClassLoaders.java", line 178, in jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass
  File "BuiltinClassLoader.java", line 581, in jdk.internal.loader.BuiltinClassLoader.loadClass
java.lang.ClassNotFoundException: java.lang.ClassNotFoundException: net.imagej.legacy.LegacyService

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "AbstractGateway.java", line 135, in org.scijava.AbstractGateway.get
  File "Context.java", line 324, in org.scijava.Context.service
  File "Types.java", line 155, in org.scijava.util.Types.load
  File "Types.java", line 234, in org.scijava.util.Types.load
  File "Types.java", line 975, in org.scijava.util.Types.iae
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/edward/Documents/software/anaconda/envs/pyimagej/lib/python3.8/site-packages/imagej/__init__.py", line 194, in init
    legacyServiceObj = ij.get('net.imagej.legacy.LegacyService')
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot load class: net.imagej.legacy.LegacyService
```

### `ij = imagej.init(['net.imagej:imagej:2.1.0', 'net.preibisch:BigStitcher:0.4.1'])`
```python
>>> ij = imagej.init(['net.imagej:imagej:2.1.0', 'net.preibisch:BigStitcher:0.4.1'])
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Traceback (most recent call last):
  File "AbstractGateway.java", line 135, in org.scijava.AbstractGateway.get
  File "Context.java", line 324, in org.scijava.Context.service
  File "Types.java", line 155, in org.scijava.util.Types.load
  File "Types.java", line 226, in org.scijava.util.Types.load
  File "ClassLoader.java", line 522, in java.lang.ClassLoader.loadClass
  File "ClassLoaders.java", line 178, in jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass
  File "BuiltinClassLoader.java", line 581, in jdk.internal.loader.BuiltinClassLoader.loadClass
java.lang.ClassNotFoundException: java.lang.ClassNotFoundException: net.imagej.legacy.LegacyService

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "AbstractGateway.java", line 135, in org.scijava.AbstractGateway.get
  File "Context.java", line 324, in org.scijava.Context.service
  File "Types.java", line 155, in org.scijava.util.Types.load
  File "Types.java", line 234, in org.scijava.util.Types.load
  File "Types.java", line 975, in org.scijava.util.Types.iae
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/edward/Documents/software/anaconda/envs/pyimagej/lib/python3.8/site-packages/imagej/__init__.py", line 194, in init
    legacyServiceObj = ij.get('net.imagej.legacy.LegacyService')
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot load class: net.imagej.legacy.LegacyService
```

**Comment by hinerm** [comment] 2021-07-28 18:37
@ctrueden @elevans OK I think I have a better understanding of the concern: if you specify a particular version of ImageJ/Fiji, there is no guarantee that you will get that component's dependencies at that version.

This happens because:
 1. `imglyb` [always includes an imglib2-imglyb endpoint](https://github.com/imglib/imglyb/blob/3065bb4da74752a3066b6a082fb777a95b6683ff/imglyb/__init__.py#L19)
 1. `imglib2-imglyb` is therefore always the "primary" endpoint
 1.  which means it is always [scope: imported](https://github.com/scijava/jgo/blob/c6681fc12674615a5c62bf2872b271d2e0c7e40c/jgo/jgo.py#L436-L439) in the jgo-bootstrapped `pom.xml`
 1. thus the final project will always have the complete `dependencyManagement` section of **the imglib2-imglyb version pinned in the imglyb release**.
 
This leads to some concerns:
- runtime failures are possible due to API or behavior changes (e.g. if I call `ij = imagej.init('net.imagej:imagej:2.0.0-rc-71')` I get rc-71's dependencies at the version specified in `imglib2-imglyb`'s parent `pom-scijava` - **not** the versions specified at time of rc-71's release)
- behavior of the same pyimagej initialization string is not guaranteed to be consistent across different versions of `imglyb`

In a perfect world:
- There would be a way to override the "primary" endpoint
- `imglib2-imglyb` completely decoupled from the scijava ecosystem to avoid any direction of skew in dependencies

This is not possible, because of the shared dependency on `imglib2` (at the very least). Soo... maybe all we can do at this point is to check each endpoint's parent in `jgo` and put up a big warning sign if the version differs from the "primary" endpoint?

**Comment by hinerm** [comment] 2021-07-30 16:24
@ctrueden how is SciJava's support for multiple contexts, with different classpaths, in a single JVM? That may be a reasonable solution - to keep the `imglib2-imglyb` and its dependencies isolated from the target ImageJ app..

**Comment by ctrueden** [comment] 2021-09-15 21:06
@hinerm and I discussed this issue a bit earlier today. Issues #32 and imagej/pyimagej#140 arose from that conversation.

Regarding multiple SciJava `Context`s: there is no special support for different `ClassLoader`s per context. You could of course do that by loading the classes yourself and feeding them to the `Context` constructor, although we haven't tried doing this, so there may be bugs. But I think multiple `Context`s won't solve the issue here—we need to be able construct a single context with all the Maven coordinates unified into a single runtime classpath.

**Comment by hinerm** [comment] 2021-09-23 18:08
With `pyimagej 1.0.2` released and `imglib2-imglyb` managed by `pom-scijava` things should be in a healthier state, but we should continue striving to eliminate common dependencies between the python and java-side libraries.

**Comment by ctrueden** [comment] 2022-02-14 19:05
I do not think there is any further work planned surrounding the issues discussed here, nor are there any really problematic limitations anymore, now that we are doing a better job with endpoint management. So I'm closing this.

**Closed by ctrueden** 2022-02-14 19:05 UTC
